Add OrderDeliveryStage
andrsuh/bombardier pull request #3
Opened 2021-09-27 11:01 UTC by MikhniukR

2021-09-27 17:28 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/external/ExternalServiceSimulator.kt
> +                val deliveryStart = (order as OrderStatus.OrderInDelivery).deliveryStartTime
order as OrderStatus.OrderInDelivery как этот каст работает?

2021-09-27 17:34 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        if (orderBeforeDelivery.status !is OrderStatus.OrderInDelivery) {
А кто будет переводить заказ в статус OrderInDelivery?

2021-09-27 17:47 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        val lastDeliveryTimeInMillis = (orderBeforeDelivery.status.deliveryStartTime + orderBeforeDelivery.deliveryDuration!!) * 1000
deliveryStartTime измеряется в millis, deliveryDuration в секундах, поэтому тут некорректно. Еще, для времени удобно использовать класс Duration

2021-09-27 17:53 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        ConditionAwaiter.awaitAtMost(lastDeliveryTimeInMillis - System.currentTimeMillis(), TimeUnit.MILLISECONDS)
deliveryDuration - это и есть количество секунд, которое мы ждем доставки по факту. Только меряется оно он моменты оплаты заказа

2021-09-27 17:53 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        ConditionAwaiter.awaitAtMost(lastDeliveryTimeInMillis - System.currentTimeMillis(), TimeUnit.MILLISECONDS)
а вот твой симулятор не генерирует задержку, а должен

2021-09-27 17:54 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +                updatedOrder.status != orderBeforeDelivery.status || serviceApi.userFinancialHistory(
тебя тут устроит любой другой статус?

2021-09-27 18:06 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +            is OrderStatus.OrderFailed -> {
кажется, что нет такого перехода, согласно этой доке - https://www.notion.so/andrsuh/83e8e3c86abd42fda4a969f7fb06ee8e

2021-09-27 18:10 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/external/ExternalServiceSimulator.kt
> +
OrderInDelivery - какой код проставляет заказ в данный стстус? На данный момент твой код получается не отрабатывает никогда. Давай подумаем кто и когда должен переводить заказ в доставку?

2021-09-27 19:20 UTC, MikhniukR commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/external/ExternalServiceSimulator.kt
> +                val deliveryStart = (order as OrderStatus.OrderInDelivery).deliveryStartTime
Просмотрел, поправил

2021-09-27 19:20 UTC, MikhniukR commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        if (orderBeforeDelivery.status !is OrderStatus.OrderInDelivery) {
Я почему-то ожидал что он уже с таким статусом предет, переписал

2021-09-27 19:20 UTC, MikhniukR commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        val lastDeliveryTimeInMillis = (orderBeforeDelivery.status.deliveryStartTime + orderBeforeDelivery.deliveryDuration!!) * 1000
Да, с ним поудобнее, только @OptIn(ExperimentalTime::class) напрягает

2021-09-27 19:22 UTC, MikhniukR commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        ConditionAwaiter.awaitAtMost(lastDeliveryTimeInMillis - System.currentTimeMillis(), TimeUnit.MILLISECONDS)
Добавил генерацию задержки

2021-09-27 19:23 UTC, MikhniukR commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +                updatedOrder.status != orderBeforeDelivery.status || serviceApi.userFinancialHistory(
Да, слишком буквально реализовал "изменение статуса"из доки, поправил

2021-09-27 19:23 UTC, MikhniukR commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +            is OrderStatus.OrderFailed -> {
Не увидел автомат статусов. Добавил статус refund и проверяю его

2021-09-27 19:25 UTC, MikhniukR commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        if (orderBeforeDelivery.status !is OrderStatus.OrderInDelivery) {
Я же правильно понимаю, что за счёт delay в simulateDelivery эта проверка будет корректно отрабатывать?

2021-09-28 11:12 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        val lastDeliveryTimeInMillis = (orderBeforeDelivery.status.deliveryStartTime + orderBeforeDelivery.deliveryDuration!!) * 1000
просто нужно использовать java.util, а не котлиновский

2021-09-28 12:16 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/external/ExternalServiceSimulator.kt
> +import kotlin.time.Duration
java.time.Duration

2021-09-28 12:16 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/external/ExternalServiceSimulator.kt
> +    @OptIn(ExperimentalTime::class)
remove

2021-09-28 12:19 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/external/ExternalServiceSimulator.kt
> +        var deliveryDuration = Duration.seconds(orderBeforeDelivery.deliveryDuration!!)
вместо всей этой сложной логики предлагаю сделать вот что - берешь время оплаты, к нему прибавляешь время доставки - это есть ожидаемое время доставки. После этого ждешь случайное время (порог - чуть больше времени ожидания реального). Потом проверяешь делать тебе рефанд, превысил ты время или нет.

2021-09-28 12:20 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        if (orderBeforeDelivery.status !is OrderStatus.OrderPayed) {
это хорошо, нравится

2021-09-28 12:21 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        serviceApi.simulateDelivery(testCtx().orderId!!)
метод блокирующий. По итогу его выполнения заказ может либо оказаться доставленым либо возвращенным. Ты совсем не тестируешь локально у себя эти флоу!

2021-09-28 12:23 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        serviceApi.simulateDelivery(testCtx().orderId!!)
для этого нужно будет в симуляторе запустить новую корутину

2021-09-28 12:24 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        if (orderBeforeDelivery.status !is OrderStatus.OrderInDelivery) {
он никогда не будет в OrderInDelivery тут. Тебе нужно начать локально у себя запускать и проверять!

2021-09-28 12:24 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        ConditionAwaiter.awaitAtMost(deliveryDuration.inWholeMilliseconds, TimeUnit.MILLISECONDS)
ждать всегда стоит чуть с запасом, а уже проверять потом по таймстемпам сошлось или нет

2021-09-28 17:21 UTC, MikhniukR commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/external/ExternalServiceSimulator.kt
> +//        val deliveryTime = Duration.ofSeconds(30)
Для тестирования без OrderSettingDeliverySlotsStage, в конце уберу

2021-10-05 12:06 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/external/ExternalServiceSimulator.kt
> +        return financialLog[userId]?.filter { it.orderId == orderId } ?: emptyList()
кайф

2021-10-05 12:08 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/external/ExternalServiceSimulator.kt
> +            delay(Random.nextLong(deliveryTime.minus(Duration.ofMillis(System.currentTimeMillis())).toMillis()))
перепроверь то, что ты здесь делаешь. из 30 секунд вычитаешь текущее время

2021-10-05 12:09 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/external/ExternalServiceSimulator.kt
> +        val deliveryTime = Duration.ofSeconds(orderBeforeDelivery.deliveryDuration!!.toLong())
expectedDeliveryTime или deliveryTimeUpperBound лучше

2021-10-05 12:10 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/external/ExternalServiceSimulator.kt
> +            delay(Random.nextLong(deliveryTime.minus(Duration.ofMillis(System.currentTimeMillis())).toMillis()))
при такой границе ожидания по сути ни одна доставка не превысит лимит. Может просто delay(deliveryDuration + случайный шум)

2021-10-05 12:11 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/external/ExternalServiceSimulator.kt
>          if (Random.nextBoolean()) {
я все еще считаю, что нет смысла сюда вносить элемент случайности.У тебя есть объективный критерий по времени.

2021-10-05 12:12 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/external/ExternalServiceSimulator.kt
> +            val currentLog = userFinancialHistory(userId, orderId)
а вот тут для теста можно внести небольшой элемент случайности

2021-10-05 12:13 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        serviceApi.simulateDelivery(testCtx().orderId!!, testCtx().userId!!)
на самом деле в нашем симуляторе не должно быть такого метода. Потому что его нет в API сервисов. Я бы предложил запускать доставку сразу после оплаты в симуляторе. А тут, когда ты заходишь в метод ты должен уже анализировать статусы

2021-10-05 12:14 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        if (orderInDelivery.status !is OrderStatus.OrderInDelivery) {
всяко нужно небольшое ожидание. И нельзя забывать, что он уже может быть доставлен к этому времени!

2021-10-05 12:16 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        val deliveryDuration = Duration.ofSeconds(orderBeforeDelivery.deliveryDuration!!.toLong())
очень сложно, почему просто не ждать deliveryDuration?

2021-10-05 12:17 UTC, andrsuh requested changes
лучше, молодец!) Но все еще требует доработок

2021-10-06 09:39 UTC, MikhniukR commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        serviceApi.simulateDelivery(testCtx().orderId!!, testCtx().userId!!)
Мне внутри в случае refund нужно сохранить операции, а без userId я этого сделать не могу. Переписал, но выглядит так себе, сохранить связь order-user в момент когда мы её знаем. Вообще странно что у нас её нет негде.

2021-10-06 09:40 UTC, MikhniukR commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/external/ExternalServiceSimulator.kt
> +            delay(Random.nextLong(deliveryTime.minus(Duration.ofMillis(System.currentTimeMillis())).toMillis()))
Да я пересмотрел, я реально усложнил с этими временами, считая что это не точно, прошло какое-то время после записи deliveryDuration, с ним проще

2021-10-11 16:30 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +        val log = CoroutineLoggingFactory.getLogger(OrderPaymentStage::class.java)
OrderDeliveryStage

2021-10-11 16:33 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderDeliveryStage.kt
> +                    log.error("Delivery order ${orderAfterDelivery.id} was shipped at time = ${orderAfterDelivery.status.deliveryFinishTime} later than expected ${expectedDeliveryTime.toMillis()}")
тест фейл или нет?

2021-10-16 12:00 UTC, closed without merging