OrderChangeItemsAfterFinalizationStage
andrsuh/bombardier pull request #4
Opened 2021-09-27 19:10 UTC by whytrall

2021-09-28 12:33 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderChangeItemsAfterFinalizationStage.kt
> +        OrderFinalizingStage.log.info("Starting change items after booked stage for order ${testCtx().orderId}")
OrderFinalizingStage - используешь логгер из другого класса

2021-09-28 12:36 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderChangeItemsAfterFinalizationStage.kt
> +        OrderFinalizingStage.log.info("Starting change items after booked stage for order ${testCtx().orderId}")
не стоит всегда запускать эту stage, сделай какой-то процент

2021-09-28 12:36 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderChangeItemsAfterFinalizationStage.kt
> +        val amount: Amount = 13
рандом

2021-09-28 12:37 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderChangeItemsAfterFinalizationStage.kt
> +        val itemToAdd = serviceApi.getAvailableItems().random()
несколько различных товаров в цикле

2021-09-28 12:38 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderChangeItemsAfterFinalizationStage.kt
> +                log.error("Did not find item with correct number of items or order not in state collecting")
из этого лога не понятно ничего, нет ни id заказа ни информации по тому какие айтемы не получилось добавить, вообще ничего

2021-09-28 12:39 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/flow/TestController.kt
> +        OrderChangeItemsAfterFinalizationStage(serviceApi),
после твоей стадии нужно сново запустить стадию финализации. Кроме того, в нее нужно добавлять проверку, нужно ли снова финализировать или нет. халтуришь...

2021-09-28 12:40 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderChangeItemsAfterFinalizationStage.kt
> +        serviceApi.bookOrder(testCtx().orderId!!)
зачем дублировать логику?

2021-09-28 12:40 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderChangeItemsAfterFinalizationStage.kt
> +        serviceApi.deleteItemFromOrder(testCtx().orderId!!, itemToAdd.id, amount)
после удаления уже не нужно book делать?

2021-09-28 12:41 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/external/ExternalServiceSimulator.kt
> +    private fun newItemsMapAfterDeletion(itemId: UUID, amount: Amount, map: Map<OrderItem, Amount>): Pair<Map<OrderItem, Amount>, Boolean> {
это страшно, давай пока избавимся от удаления

2021-09-28 12:53 UTC, whytrall commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderChangeItemsAfterFinalizationStage.kt
> +        serviceApi.deleteItemFromOrder(testCtx().orderId!!, itemToAdd.id, amount)
Obsolete из-за следующего комментария

2021-10-05 12:18 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderChangeItemsAfterFinalizationStage.kt
> +        serviceApi.bookOrder(testCtx().orderId!!)
выше написал как это сделать проще

2021-10-05 12:20 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderChangeItemsAfterFinalizationStage.kt
> +            log.info("OrderChangeItemsAfterFinalizationStage will not be executed")
для какого заказа?

2021-10-05 12:20 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderChangeItemsAfterFinalizationStage.kt
> +        repeat(Random.nextInt(1, 50)) {
давай чуть меньше) например, 10?

2021-10-05 12:22 UTC, andrsuh commented on src/main/kotlin/com/itmo/microservices/demo/bombardier/stages/OrderChangeItemsAfterFinalizationStage.kt
> +            serviceApi.bookOrder(testCtx().orderId!!)
зачем? Это респонсибилити стадии финализации

2021-10-05 12:22 UTC, andrsuh requested changes
дорабатывай)

2021-10-11 16:38 UTC, merged